services:
  api:
    build: .
    container_name: ahadu-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["sh", "/app/wait-for-db.sh", "db", "./main"]


  db:
    image: postgres:15-alpine
    container_name: ahadu-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: saas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
